services:

  - wikipedia:
      path: "https://en.wikipedia.org/wiki/User:%s"
      mode: HTTP
      category: community
      timeout: 5
      container: "#mw-content-text" # Added because Go code expects a container
      selectors:
        error: "div.cdx-message--warning.mw-userpage-userdoesnotexist.cdx-message.cdx-message--block > div"
        bio: "div.mw-content-ltr.mw-parser-output > p"

  - luarocks:
      path: "https://luarocks.org/modules/%s"
      mode: HTTP
      category: development
      timeout: 5
      container: "body" # Added a fallback top-level container for luarocks
      selectors:
        error: ".not_found_page base_page .base_widget"
        github: "div.page_header_inner > div.right_tools > div.social_links > a"
        join: "div.metadata_columns > div > div:nth-child(2) > span[attr=title]"

  - lichess:
      path: "https://lichess.org/@/%s"
      mode: HTTP 
      category: gaming
      timeout: 5
      container: "body"
      selectors:
        error: "#main-wrap > main > h1"
        joined: "#us_profile > div.profile-side > div > div > p:nth-child(2)"
        bio: "#us_profile > div.profile-side > div > p"
        country: "#us_profile > div.profile-side > div > div > div.location"
        bullet: "#main-wrap > main > aside > div > a:nth-child(1) > span > rating > strong"
        blitz: "#main-wrap > main > aside > div > a:nth-child(2) > span > rating > strong"
        rapid: "#main-wrap > main > aside > div > a:nth-child(3) > span > rating > strong"
        classical: "#main-wrap > main > aside > div > a:nth-child(4) > span > rating > strong"
        puzzles: "#main-wrap > main > aside > div > a:nth-child(7) > span > rating > strong"

  - codechef:
      path: "https://codechef.com/users/%s"
      mode: HTTP
      category: development
      timeout: 5
      container: "body"
      redirects_to: "https://www.codechef.com/"
      selectors:
        error: ""
        rating: "#rating-block-all > div.rating-header.text-center > div.rating-number"
        global-rank: "#rating-block-all > div.rating-ranks > ul > li:nth-child(1) > a > strong"
        country-rank: "#rating-block-all > div.rating-ranks > ul > li:nth-child(2) > a > strong"
        country: "body > main > div > div > div > div > div > section.user-details > ul > li:nth-child(2) > span > span"

  - twitter:
      path: "https://api.vxtwitter.com/%s"
      mode: JSON
      category: social_media
      timeout: 5
      selectors:
        created_at: "created_at"
        description: "description"
        followers: "followers_count"
        following: "following_count"
        location: "location"
        pfp: "profile_image_url"
        tweets: "tweet_count"

#  - reddit:
#      path: "https://old.reddit.com/u/%s"
#      mode: HEADED
#      container: "body"
#      category: social_media
#      timeout: 15
#      sleep: 60
#      cookies:
#        over18: "1"
#      selectors: 
#        error: "#classy-error > h1"
#        post-karma: "body > div.side > div:nth-child(1) > div > span:nth-child(2)"
#        comment-karma: "body > div.side > div:nth-child(1) > div > span.karma.comment-karma"
#        joined: "body > div.side > div:nth-child(1) > div > div.bottom > span > time[attr=title]"

  - github:
      path: "https://api.github.com/users/%s"
      mode: JSON
      category: development
      timeout: 5
      headers:
        X-GitHub-Api-Version: "2026-03-10"

  - monkeytype:
      path: "https://api.monkeytype.com/users/%s/profile?isUid=false"
      mode: JSON
      category: community
      timeout: 5

  - chessdotcom:
      path: "https://www.chess.com/callback/leagues/user-league/search/%s"
      mode: JSON
      category: gaming
      timeout: 5

  - tryhackme:
      path: "https://tryhackme.com/api/v2/public-profile?username=%s"
      mode: HEADLESS_JSON
      category: development
      timeout: 15
      sleep: 5
      selectors:
        avatar: "data.avatar"
        username: "data.username"
        level: "data.level"
        country: "data.country"
        about: "data.about"
        linkedin: "data.linkedInUsername"
        github: "data.githubUsername"
        twitter: "data.twitterUsername"
        instagram: "data.instagramUsername"
        website: "data.personalWebsite"
        reddit: "data.redditUsername"
        discord: "data.discordUsername"
        calendly: "data.calendlyUrl"
        total-points: "data.totalPoints"
        badges: "data.badgesNumber"
        rooms-completed: "data.completedRoomsNumber"
        streak: "data.streak"
        rank: "data.rank"
        top-percentage: "data.topPercentage"
        top-ten-percent: "data.isInTopTenPercent"
        badge-image: "data.badgeImageURL"
        role: "data.userRole"
        league-tier: "data.leagueTier"
        joined: "data.dateSignUp"
      

