services:
  - leetcode:
      category: development
      path: https://leetcode.com/graphql
      method: POST
      content_type: application/json
      mode: JSON
      timeout: 10
      body: '{"query":"query userPublicProfile($username: String!) { matchedUser(username: $username) { username profile { realName aboutMe userAvatar countryName company school ranking } } }","variables":{"username":"%s"}}'
      selectors:
        name: data.matchedUser.profile.realName
        bio: data.matchedUser.profile.aboutMe
        avatar: data.matchedUser.profile.userAvatar
        country: data.matchedUser.profile.countryName
        company: data.matchedUser.profile.company
        school: data.matchedUser.profile.school
        ranking: data.matchedUser.profile.ranking

  - anilist:
      category: community
      path: https://graphql.anilist.co
      method: POST
      content_type: application/json
      mode: JSON
      timeout: 10
      body: '{"query":"query{User(name:\"%s\"){id name about avatar{large} bannerImage}}"}'
      selectors:
        id: data.User.id
        about: data.User.about
        avatar: data.User.avatar.large
        banner: data.User.bannerImage

  - albicla:
      category: social_media
      path: https://albicla.com/%s/post/1
      mode: HTTP
      timeout: 10
      container: "html"
      selectors:
        error: 'body:contains("404 Nie znaleziono użytkownika")'

  - discord:
      category: community
      path: https://discord.com/api/v9/unique-username/username-attempt-unauthed
      method: POST
      content_type: application/json
      mode: JSON
      timeout: 5
      headers:
        referer: https://discord.com/register
      body: '{"username": "%s"}'
      selectors:
        taken: taken

  - beatstars:
      category: music
      path: https://core.prod.beatstars.net/auth/graphql
      method: POST
      content_type: application/json
      mode: JSON
      timeout: 10
      body: '{"operationName":"identifierAvailable","variables":{"identifier":"%s"},"query":"query identifierAvailable($identifier: String!) { identifierAvailable(identifier: $identifier) { ...AccountBasicInfo } } fragment AccountBasicInfo on IsIdentifierAvailableResponse { available profileDetails { username artwork { fitInUrl } } }"}'
      selectors:
        username: data.identifierAvailable.profileDetails.username
        avatar: data.identifierAvailable.profileDetails.artwork.fitInUrl
